TARGET=test.exe
CC=gcc

HEADERS=-I./headers/

PREF_SRC=src
PREF_OBJ=build

SRC = $(wildcard $(PREF_SRC)/*.c)
OBJ = $(patsubst $(PREF_SRC)/%.c, $(PREF_OBJ)/%.o, $(SRC))

release : CFLAGS=-Wno-narrowing -Wno-pointer-arith -O0 -g
release : $(TARGET)

$(TARGET) : $(OBJ)
	$(CC) $(HEADERS) $(CFLAGS) $^ -o $@

$(PREF_OBJ)/%.o : $(PREF_SRC)/%.c
	$(CC) $(HEADERS) $(CFLAGS) -c $^ -o $@

clean :
	del /f $(PREF_OBJ)\*.o *.exe
